#pragma once
// Abstraction for platform specific types

// Rendering device
#define				PDEVICE			LPDIRECT3DDEVICE9 
#define				PVERTEXBUFFER	LPDIRECT3DVERTEXBUFFER9
#define				PINDEXBUFFER	LPDIRECT3DINDEXBUFFER9
#define				SURFACE_DESC	D3DSURFACE_DESC
#define				PTEXTURE		LPDIRECT3DTEXTURE9