
//Animation indexes (Idx)
#define 	ANM_BK_CITY_SPR_WATER1   0
#define 	ANM_BK_CITY_SPR_NEARCAMERA   1
#define 	ANM_BK_CITY_SPR_NIGHT   2
#define 	ANM_BK_CITY_SPR_SUNSET   3
#define 	ANM_BK_CITY_SPR_NIGHT_RAIN   4
#define 	ANM_BK_CITY_SPR_SUNSET_RAIN   5
#define 	ANM_BK_CITY_SPR_DAY   6
#define 	ANM_BK_CITY_SPR_DAY_RAIN   7

//Animation names (ID)
#define 	ANMID_BK_CITY_SPR_WATER1   "WATER1"
#define 	ANMID_BK_CITY_SPR_NEARCAMERA   "NEARCAMERA"
#define 	ANMID_BK_CITY_SPR_NIGHT   "NIGHT"
#define 	ANMID_BK_CITY_SPR_SUNSET   "SUNSET"
#define 	ANMID_BK_CITY_SPR_NIGHT_RAIN   "NIGHT_RAIN"
#define 	ANMID_BK_CITY_SPR_SUNSET_RAIN   "SUNSET_RAIN"
#define 	ANMID_BK_CITY_SPR_DAY   "DAY"
#define 	ANMID_BK_CITY_SPR_DAY_RAIN   "DAY_RAIN"
