
//Animation indexes (Idx)
#define 	ANM_LIGHTS_SPR_PROJECTED_DIR   0
#define 	ANM_LIGHTS_SPR_IES   1
#define 	ANM_LIGHTS_SPR_SHADOWS   2
#define 	ANM_LIGHTS_SPR_TEST_LIGHTS   3
#define 	ANM_LIGHTS_SPR_CHAR_SHADOWS   4
#define 	ANM_LIGHTS_SPR_GI_LIGHTS   5

//Animation names (ID)
#define 	ANMID_LIGHTS_SPR_PROJECTED_DIR   "PROJECTED_DIR"
#define 	ANMID_LIGHTS_SPR_IES   "IES"
#define 	ANMID_LIGHTS_SPR_SHADOWS   "SHADOWS"
#define 	ANMID_LIGHTS_SPR_TEST_LIGHTS   "TEST_LIGHTS"
#define 	ANMID_LIGHTS_SPR_CHAR_SHADOWS   "CHAR_SHADOWS"
#define 	ANMID_LIGHTS_SPR_GI_LIGHTS   "GI_LIGHTS"
