
//Animation indexes (Idx)
#define 	ANM_PARTICLES_SPR_IMPACT_FIRE1   0
#define 	ANM_PARTICLES_SPR_IMPACT_SMOKE1   1
#define 	ANM_PARTICLES_SPR_EXPLO_FIRE1   2
#define 	ANM_PARTICLES_SPR_FIRE_PARTS1   3
#define 	ANM_PARTICLES_SPR_TAILS   4

//Animation names (ID)
#define 	ANMID_PARTICLES_SPR_IMPACT_FIRE1   "IMPACT_FIRE1"
#define 	ANMID_PARTICLES_SPR_IMPACT_SMOKE1   "IMPACT_SMOKE1"
#define 	ANMID_PARTICLES_SPR_EXPLO_FIRE1   "EXPLO_FIRE1"
#define 	ANMID_PARTICLES_SPR_FIRE_PARTS1   "FIRE_PARTS1"
#define 	ANMID_PARTICLES_SPR_TAILS   "TAILS"
