
//Animation indexes (Idx)
#define 	ANM_TITLE_SCREEN_SPR_LOGO   0
#define 	ANM_TITLE_SCREEN_SPR_TROOPERS   1
#define 	ANM_TITLE_SCREEN_SPR_TROOPERS_LOOP   2
#define 	ANM_TITLE_SCREEN_SPR_BACK   3
#define 	ANM_TITLE_SCREEN_SPR_VIGNETTE   4
#define 	ANM_TITLE_SCREEN_SPR_TROOPERS2   5
#define 	ANM_TITLE_SCREEN_SPR_TROOPERS2_LOOP   6
#define 	ANM_TITLE_SCREEN_SPR_CONSOLE_LOGOS   7

//Animation names (ID)
#define 	ANMID_TITLE_SCREEN_SPR_LOGO   "LOGO"
#define 	ANMID_TITLE_SCREEN_SPR_TROOPERS   "TROOPERS"
#define 	ANMID_TITLE_SCREEN_SPR_TROOPERS_LOOP   "TROOPERS_LOOP"
#define 	ANMID_TITLE_SCREEN_SPR_BACK   "BACK"
#define 	ANMID_TITLE_SCREEN_SPR_VIGNETTE   "VIGNETTE"
#define 	ANMID_TITLE_SCREEN_SPR_TROOPERS2   "TROOPERS2"
#define 	ANMID_TITLE_SCREEN_SPR_TROOPERS2_LOOP   "TROOPERS2_LOOP"
#define 	ANMID_TITLE_SCREEN_SPR_CONSOLE_LOGOS   "CONSOLE_LOGOS"
