#pragma once

#include "LevelDefines.h"
#include "ActorTypes.h"
#include "ActorTemplate.h"
#include "components/SpriteActorComp.h"
#include "components/WeaponsComp.h"
#include "components/ActorAIComp.h"

// suspend flags used on actor->nSuspendedFlag 
#define K_LVL_SUSPENDFLAG_NONE 0
// player suspended - fallen offscreen
#define K_LVL_SUSPENDFLAG_OUTSIDE_SCREEN 1

// Actor class - players and enemies
class CActor : public IActiveInterface
{
	///--- COMPONENTS --- 
	/// Pointer components get deallocated by the actor, referenced ones are global so we don't touch them:
private:
	CSpriteActorComponent*		c_graphics;					// graphics component that handles all painting and animation stuff
	CWeaponsComponent*			c_weapons;					// graphics and logic component that handles the weapons
	CActorAIComponent*			c_AI;						// AI component that handles actor controlling (player or computer)

	CLevel&						level;						// Reference to current level (__Sim())
public:
	CActorTemplate				_template;					// holds data about each actor, copied from source templates (xml) and probably modified by enhancements
	CActorTemplate				_template_ini;				// holds initial template that we reset to when changing the weapon or adding non permanent enhancements

	//#TODO: convert to verse/voice component or class:
	EActorSoundVerse			eLastPlayedVerse;			//last played sound verse
	float						fVerseCooldown;				//don't play the same verse if cooldown > 0.0f
	int							nLastPlayedVerseSndIdx;		//last played sound idx

	VecProj						vHeart;						// 3d heart position used for visibility tests and weapon direction
	UINT16						collisionFlags;				// tells us where we have collisions (K_DIRFLAG_...)
	bool						bHasGravity;				// does it have gravity?

	Vec3						pos_last;					// position on last frame
	Vec2						vAim;						// final aim vector
	Vec2						speed;						// Internal character speed for moving
	Vec2						vSpeedImpulse;				// External speed for pushback (has friction)

	float						fLife;
	float						fArmor;
	float						fFOVPercent;				// actor FOV for detecting enemies [0..1] => [0..2PI]

	CDamageOverTime				cDamageOverTime;			//#TODO: de schimbat in ceva si cu conotatii pozitive (healing, perk, etc)
	EActorAttackState			eAttackStatus;				// weapon handling status (shooting, shootalt, reloading, etc)

	bool						bCrouched;			
	EGenericState				nRolling;					//0-ready, 1-rolling, 2-finished and waiting reset (direction key up)

	float						fStunTimer; 
	UINT32						nLastDamageTakenFromUID;	//UID that gave actor last damage 
	
	UINT32						nSuspendedFlags;			// AI suspended (usually for main players to cut off input when outside screen). See flags for reason.
	float						fSuspendedTimer;			// counts from when suspended flags is set
	bool						bSuspendInput;				// if set keyboard input is ignored but AI works (could be a suspended flag)

	IActiveInterface*			pClosestTouchable;			// currently focused interactible object
	EGenericState				eInteractState;				// state of interaction (NOTSET=not interacting, READY-selecting action, EXECUTING-started action, FINISHED-interact finished)
	int							nInteractOptionsSelIdx;		// index in arrInteractOptions
	CFixedArray<CScriptAction, 16>	arrInteractOptions;		// empty when not interacting. gathers all interaction options from object, character feats, inventory objects, etc

	int				nPlayerOrdinal;	//player index (0-max_players_cnt)
	int				nControllerInstanceID; //player controller ID (-1 for empty)

public:
	// CTOR. Allocate the components when calling the constructor. They will get deallocated by CActor.
	CActor( Vec2 vnPos, CActorTemplate* pActorTemplate, int nID,
		CLevel& refLevel,
		CSpriteActorComponent* pComGraphics, 
		CWeaponsComponent* pComWpn,
		CActorAIComponent* pComAI);
	// DTOR
	~CActor();

	inline const EActiveInterfaceType	GetClassType() const override {
		return K_LVL_IAI_TYPE_ACTOR;
	}

private:
	// Initializes CActor with specified template and sets all the data it needs. Returns false if it fails
	bool						InitFromTemplate( CActorTemplate * pActorTemplate );
	// Sets the actor's weapon and template upgrades and limitations generated by the weapon, adding them to actor initial template (after spawning, without weapons)
	void						ApplyWeaponTemplate( CWeapon * pWeapon );
	// decides the current attack state of the actor based on AI commands and weapon status
	void						ComputeAttackStatus();
	// Processes the commands from the AI component. Needs access to level for effects.
	void						ProcessAICommands();
	// Physics Integrator, converts speeds to movement and handles collisions
	void						DoMove( float dTime );
	// Processes extra stuff after moving (interactibles, pArea ownership, etc)
	void						ProcessExtras();
	// Sets animations based on behaviour
	void						ProcessAnimations();
	// checks weapon states to see if we must generate the bullets
	// \returns: true if shot, false if it didn't
	bool						CheckShoot();

public:
	// Sets a new AI state
	void						SetAIState( CAIState* pNewState );
	// Sets a new AI state
	bool						SetAIState( WCHAR * strStateName );
	// Returns current behavior in current AI state
	inline EAIBehaviorType		GetCurrentBehavior() { return c_AI->GetCurrentBehavior(); };
	// Gets pointer to weapons component
	inline CWeaponsComponent*	Weapons() { return c_weapons; }
	// Gets pointer to AI component
	inline const CActorAIComponent*  	GetAI() const { return c_AI; }
	// tells if actor is alive (health > 0) and not hidden or deallocated, or inactive
	bool						IsAlive() override;
	// returns the enabled flag (ignored by updates and all)
	bool						IsEnabled();
	void						SetPos( Vec3 newPos ) override;
	void						Move( Vec3 delta ) override;
	// Useless for actors
	void						SetAI( EAIstate newstate ) override;
	// returns projected position of the central point
	inline Vec2					GetPosHeart() const { return vHeart.xy_proj; }
	// returns 3d position of the heart central point
	inline VecProj				GetPosHeart3D() const { return vHeart; }
	// Updates specified Actor AI. Returns busy state TRUE if actor has jobs to do or false if actor is still
	void						Update( float dTime );
	// Paints the actor on a specific color channel
	void						Paint( ETexChannel eChannel = K_TEXCHAN_COLORMAP );
	// returns aim vector
	inline Vec2					GetAimVec() { return vAim; };
	// returns speed vector
	inline Vec2					GetSpeedVec() { return speed; };
	// returns animation direction on X (flipped or not, decided by the graphics component)
	inline int					GetVisualFlipDirX() { return c_graphics->GetFlipDirX(); }
	// Returns the gun mount position. bDualHanded tells if we are looking for the dual handed mount or single handed mount.
	// mountIndex is usually used when looking for the position of single handed weapons in dualWield mode (hand on the left)
	VecProj						GetWeaponMountWorld( int nHands, int mountIndex = 0 );
	// Returns the gun muzzle position in World coordinates.
	// \param mountIndex - 0 for most weapons, 1 for second weapon in dual wielding stances
	VecProj						GetWeaponMuzzleWorld( int nHands, int mountIndex /*= 0 */ );
	// Returns muzzle point for CURRENT weapon
	VecProj						GetCurWeaponMuzzleWorld( int mountIndex = 0 );
	// Equips a weapon by index in weapons component
	void						EquipWeapon( EWpnSlot wpnSlot );
	// sets graphics anim set
	void						SetAnimSet( int n_anim_set ) { c_graphics->SetAnimSet( n_anim_set ); }
	// Plays the actor verse from the template handling the positional attenuation
	void						PlaySoundVersePos( D3DXVECTOR2 vListenerPos, EActorSoundVerse sVerse, bool bPlayIfNotPlayingOnly = false );
	// Updates possible actions list when interacting with something
	// Looks into the inventory, the touchable and the actor specs/template for specific actions
	void						BuildActionsList();
	// Clears the current actions list
	void						ClearActionsList();

	// Use it to damage enemies and player
	// @fHitPointsTaken - negative value - kills it immediately
	// RETURNS: damage made, type of material hit.
	CBulletHitReturnData		HitActor( CBullet * pBullet, Vec2 * pvProjectileMomentum = nullptr );
	//hits the actor with other things than bullets
	CBulletHitReturnData		HitActor( float fDamage, UINT32 dwOwnerUID, EActorClass eOwnerClass, Vec2 *vDir = null, UINT32 dwBulletFlags = 0, int nArmorPiercingRating = 100, float fStunDuration = 0.0f );
	// Stuns the actor
	void						SetStun( float fStunDuration );


public:	
	void PostConstructionInit() override;
	void BeginPlay() override;
	void EndPlay() override;
};
