#pragma once

#include "ActiveInterface.h"
#include "components/CollAIComp.h"

//--- COLLISION ZONES ---
//collision boxes flags
#define K_LVL_COLLFLAG_NONE				0
//collision generated by the engine (level bounds)
#define K_LVL_COLLFLAG_LEVEL_BOUNDS		1
//is the collision flag a solid one? (Can I spawn the player on it?)
#define K_LVL_COLLFLAG_SOLID			2 

enum ECollType {
	K_COLLTYPE_NOTSET = 0,
	K_COLLTYPE_SOLID,
	K_COLLTYPE_TRIGGER,
	K_COLLTYPE_PARTICLEGEN,
};

class CCollisionShape : public IActiveInterface
{
public:
	CCollAIComponent*		c_AI;			// AI component
public:
	ECollType				eType;			
	bool					castShadows;
	BYTE					ubFlags;		//type flags for collisions (solid, box, etc)
	BYTE					collFlags;		//collision direction flags (direction of collision if we need to collide from E but not from W)

	CCollisionShape( CCollAIComponent* AIcomponent );
	~CCollisionShape();

	const EActiveInterfaceType GetClassType() const {
		return K_LVL_IAI_TYPE_COLSHAPE;
	}

	void					SetPos(Vec3 newPos) override;
	void					Move(Vec3 delta) override;

	void					PostConstructionInit() override;
	void					BeginPlay() override;
	void					EndPlay() override;

	void					Update( float dTime );
};
