//
// Generated by Microsoft (R) D3DX9 Shader Compiler 
//
// Parameters:
//
//   float3 fvLightPosition;
//   row_major float4x4 matViewProjection;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   matViewProjection c0       4
//   fvLightPosition   c4       1
//

    vs_2_0
    dcl_position v0
    dcl_texcoord v1
    dcl_texcoord1 v2
    mul r0, v0.y, c1
    mad r0, v0.x, c0, r0
    mad r0, v0.z, c2, r0
    mad oPos, v0.w, c3, r0
    add oT2.xyz, -v0, c4
    mov oT0.xy, v1
    mov oT1.xy, v2

// approximately 7 instruction slots used
