//
// Generated by Microsoft (R) D3DX9 Shader Compiler 
//
// Parameters:
//
//   float4 RTTtex_xywh;
//   float4 RTTxywh;
//   row_major float4x4 matViewProjection;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   matViewProjection c0       4
//   RTTxywh           c4       1
//   RTTtex_xywh       c5       1
//

    vs_2_0
    dcl_position v0
    dcl_normal v1
    dcl_color v2
    dcl_texcoord v3
    mul r0, v0.y, c1
    mad r0, v0.x, c0, r0
    mad r0, v0.z, c2, r0
    mad oPos, v0.w, c3, r0
    add r0.xy, v0, -c4
    rcp r0.z, c4.z
    rcp r0.w, c4.w
    mul r0.xy, r0, r0.zwzw
    mad oT1.xy, r0, c5.zwzw, c5
    mov oD0, v2
    mov oT0.xy, v3
    mov oT2.xyz, v1

// approximately 12 instruction slots used
