
//Animation indexes (Idx)
#define 	ANM_PROPS_SPR_MISC   0
#define 	ANM_PROPS_SPR_CHARACTERS   1
#define 	ANM_PROPS_SPR_BULLETS_NOANIM   2
#define 	ANM_PROPS_SPR_BULLETS_LIGHTS   3
#define 	ANM_PROPS_SPR_BULLET_ANIM1   4
#define 	ANM_PROPS_SPR_CHRISTMAS_ANIM   5

//Animation names (ID)
#define 	ANMID_PROPS_SPR_MISC   "MISC"
#define 	ANMID_PROPS_SPR_CHARACTERS   "CHARACTERS"
#define 	ANMID_PROPS_SPR_BULLETS_NOANIM   "BULLETS_NOANIM"
#define 	ANMID_PROPS_SPR_BULLETS_LIGHTS   "BULLETS_LIGHTS"
#define 	ANMID_PROPS_SPR_BULLET_ANIM1   "BULLET_ANIM1"
#define 	ANMID_PROPS_SPR_CHRISTMAS_ANIM   "CHRISTMAS_ANIM"
