//
// Generated by Microsoft (R) HLSL Shader Compiler 9.22.949.2248
//
// Parameters:
//
//   float4 RTTxywh;
//   row_major float4x4 matViewProjection;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   matViewProjection c0       4
//   RTTxywh           c4       1
//

    vs_3_0
    dcl_position v0
    dcl_color v1
    dcl_position o0
    dcl_color o1
    dcl_texcoord o2.xy
    dcl_texcoord1 o3
    mul r0, c1, v0.y
    mad r0, v0.x, c0, r0
    mad r0, v0.z, c2, r0
    mad o0, v0.w, c3, r0
    rcp r0.x, c4.z
    add r0.yz, -c4.xxyw, v0.xxyw
    mul o2.x, r0.x, r0.y
    rcp r0.x, c4.w
    mul o2.y, r0.z, r0.x
    mov o1, v1
    mov o3, v0

// approximately 11 instruction slots used
