#pragma once

#include "ActiveInterface.h"

//--- COLLISION ZONES ---
#define K_LVL_COLL_FOW_COLOR 0xff202950
//collision boxes flags
#define K_LVL_COLLFLAG_NONE				0
//collision generated by the engine (level bounds)
#define K_LVL_COLLFLAG_LEVEL_BOUNDS		1
//is the collision flag a solid one? (Can I spawn the player on it?)
#define K_LVL_COLLFLAG_SOLID			2 


#define K_LVL_COLL_TYPE_SOLID 0
//STAIRS - urca cu jump pe trepte (sau pe cutii)
#define K_LVL_COLL_TYPE_STAIRS 1
#define K_LVL_COLL_TYPE_WATER 2
//LADDER - urca pe ea cu alta animatie (deci nu urca cu jump)
#define K_LVL_COLL_TYPE_LADDER 3
//cutia e exact stairs dar stair size e inaltimea ei
#define K_LVL_COLL_TYPE_BOX 4
//TRIGGER - actioneaza scripturi in fn de mesaje
#define K_LVL_COLL_TYPE_TRIGGER 5
//PARTICLE SYSTEMS
#define K_LVL_COLL_TYPE_PARTICLE_GENERATOR 6
//FOG_OF_WAR - un fel de fog of war care apare peste camerele nedescoperite
#define K_LVL_COLL_TYPE_FOG_OF_WAR 7
//COVER - boxuri dupa care te poti ascunde
#define K_LVL_COLL_TYPE_COVER 8
//MOVING PLATFORM - solid, usually elevators (not safe for respawn or physics)
#define K_LVL_COLL_TYPE_MOVING_PLATFORM 9
//LEDGE - solid for bullets, like a BOX for actors
#define K_LVL_COLL_TYPE_LEDGE 10


class CCollisionShape : public IActiveInterface
{
public:
	int		type;
	bool	castShadows;
	int		stairSize;		//folosit la trepte si cutii
	BYTE	ubFlags;		//flags for collisions

	byte	collFlags;		//collision direction flags (de ex la stairs se pune flags = K_DIR_FLAG_DOWN pt ca are coliziune doar la cadere)
	//lista de actori care stau pe collision shape-ul acesta
	CGrowableArray<CActor*> touchingActors;
	//Removes touching actor from list. Returns: true if found, false if not
	bool					RemoveTouchingActor(CActor* actor);

	//CTOR/DTOR
	CCollisionShape() : type(K_LVL_COLL_TYPE_SOLID), castShadows(false), stairSize(0.0f), collFlags(K_DIRFLAG_ALL), ubFlags(K_LVL_COLLFLAG_SOLID)
	{}

	const int GetClassType() const {
		return K_LVL_IAI_TYPE_COLSHAPE;
	}

	void SetPos(D3DXVECTOR2 newPos) override;
	void Move(D3DXVECTOR2 delta) override;
	void SetAngle(float fnAngle) override
	{
		fAngle = fnAngle;
	}

	void BeginPlay() override;
	// Initializes internal data
	void InitInternalData();
};
